### ISSUE TITLE
some bugs of GIRF

### ISSUE THREAD

**Issue by Cherry0809** [angusmoore/tvarGIRF#7]
Hi~Moore,I have a bug when I run the following code related to GIRF:

[code.txt](https://github.com/angusmoore/tvarGIRF/files/3684103/code.txt)
[data1.xlsx](https://github.com/angusmoore/tvarGIRF/files/3684104/data1.xlsx)

the bugs demostrate that "Error in if (round(z2[i - thDelay], round_digits) <= Thresh[1]) { : 
  missing value where TRUE/FALSE needed"

And I have tied to figure out the problem but ended up with failure.
Could you please give me some help ? Thanks for your kind consideration.

**Comment by angusmoore** [comment]
Hi Cherry0809,

What you are encountering is that the `tvarGIRF` library does not support TVARs with external transition variables (e.g. you have used `thVar = tvn` in creating your threshold VAR. Because GIRFs need to simulate the data, tvarGIRF can't handle external transition variables because it doesn't know how to simulate that series.

(The error message you got obviously didn't explain that - I've fixed that up, thank you. It will now provide a more helpful error message.)

**Comment by Cherry0809** [comment]
Dear Moore,

Thank you so much for your replay.
It seems that I have to turn to other codes that support TVARs with external transition variables.
Or could you please give me some better advice? 


Yours sincerely,
Jaden


 
 
------------------ Original ------------------
